### ISSUE TITLE
Refusing to install cloudwatch

### ISSUE THREAD

**Issue by vijaypatnana** [WeAreCloudar/chef-cloudwatch-logs#11]
Hi,

I have been using this cookbook heavily to ingest logs to cloudwatch. but in recent times, when I am trying to run the cookbook I am getting this error below. 

Starting Chef Client, version 12.17.44
resolving cookbooks for run list: ["cloudwatch-logs"]
Synchronizing Cookbooks:
 - cloudwatch-logs (0.0.7)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: cloudwatch-logs::default
 * log[Refusing to install CloudWatch Logs because no logs have been configured. (node['cwlogs']['logfiles'] is nil)] action write

Please let me know if you are aware of this error. my configuration is looking good, not sure what I am doing wrong. 

Thanks
Vijay

**Comment by benbridts** [comment]
Hi,

Are you sure that your configuration is correct? That error looks like it's failing on this condition:

https://github.com/WeAreCloudar/chef-cloudwatch-logs/blob/master/recipes/default.rb#L6

Kind regards,
Ben

**Comment by vijaypatnana** [comment]
Hi Ben,

This is my configuration in the chef role file. Let me know if anything is wrong. Thanks in Advance!

```
"cwlogs": {
      "logfiles": {
        "api-log": {
          "log_group_name": "javalogs",
          "log_stream_name": "{hostname}-api.log",
          "file": "/logs/api.log",
          "datetime_format": "%Y-%m-%d'T'%H:%M:%S",
          "initial_position": "end_of_file"
        }
      }
    }
```

**Comment by benbridts** [comment]
@vijaypatnana Sorry, I forgot to look at this (I'm not using it myself anymore) did you find a solution?

Kind regards,
Ben
